# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac3417f8983f65ac9a9a1ea777d73542b0fd744dabd2aef27eedfca42f1f43802232b0b083557b5706a83c27d1876deb4b92dde91b0e9b10f43ccef690356a41

test:
  secret_key_base: 26c9c1822cc40f5039819a6f3f08a4f821de8c02cd3cd43a13330f69e8f09ef4af8005c240f94f4ea46ad0d9ac8c561a0bba693f1f7c221ff9238a5baab5a9e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
